sonar.projectKey=testprojekt2_Git_Net_1
sonar.working.directory=C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1
sonar.pullrequest.cache.basepath=C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1

5BC956E4-5A91-4F00-A341-7DE73F09EFF9.sonar.projectKey=testprojekt2_Git_Net_1:5BC956E4-5A91-4F00-A341-7DE73F09EFF9
5BC956E4-5A91-4F00-A341-7DE73F09EFF9.sonar.projectName=NetConsoleApp1
5BC956E4-5A91-4F00-A341-7DE73F09EFF9.sonar.projectBaseDir=C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1
5BC956E4-5A91-4F00-A341-7DE73F09EFF9.sonar.sourceEncoding=utf-8
5BC956E4-5A91-4F00-A341-7DE73F09EFF9.sonar.tests=
5BC956E4-5A91-4F00-A341-7DE73F09EFF9.sonar.sources=\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\Program.cs",\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\Program2.cs",\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\dotnet",\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\README.md",\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\.vscode\\launch.json",\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\.vscode\\tasks.json",\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\obj\\NetConsoleApp1.csproj.nuget.dgspec.json",\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\obj\\project.assets.json",\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\.git\\workflows\\build.yml",\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\.git\\workflows\\sonarqube.yml",\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\bin\\Debug\\net8.0\\NetConsoleApp1.deps.json",\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\bin\\Debug\\net8.0\\NetConsoleApp1.runtimeconfig.json",\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\bin\\Release\\net8.0\\NetConsoleApp1.deps.json",\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\bin\\Release\\net8.0\\NetConsoleApp1.runtimeconfig.json",\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\obj\\Debug\\net8.0\\NetConsoleApp1.sourcelink.json",\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\obj\\Release\\net8.0\\NetConsoleApp1.sourcelink.json"

5BC956E4-5A91-4F00-A341-7DE73F09EFF9.sonar.stylecop.projectFilePath=C:\\sonar-scanner-10.1.0.110937-net\\SonarScanner.MSBuild.dll
5BC956E4-5A91-4F00-A341-7DE73F09EFF9.sonar.cs.analyzer.projectOutPaths=\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\.sonarqube\\out\\0"
5BC956E4-5A91-4F00-A341-7DE73F09EFF9.sonar.cs.roslyn.reportFilePaths=\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\.sonarqube\\out\\0\\Issues.json"
5BC956E4-5A91-4F00-A341-7DE73F09EFF9.sonar.cs.scanner.telemetry=\
"C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\.sonarqube\\out\\0\\Telemetry.json"

5BC956E4-5A91-4F00-A341-7DE73F09EFF9.sonar.working.directory=C:\\RAZVOJ\\.NETPROJECTS\\NetConsoleApp1\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=5BC956E4-5A91-4F00-A341-7DE73F09EFF9

